version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  weather-service-main:
    jobs:
      - build-and-test
